# Generated by Django 4.1 on 2022-09-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_remove_tempuser_device_id_alter_tempuser_d_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='p_type',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='FirebaseDetails',
            fields=[
                ('d_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.alldevices')),
                ('fcm', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
